Disabled building of GNOME2 Applet in gnome-shell-extension branch.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21,7 +21,7 @@ fi
 parse_in()
 {
 echo "Creating ${1%%.in}..."
-$sed -e "s#?cc#$cc#g" -e "s#?gtk_cflags#$gtk_cflags#g" -e "s#?gtk_libs#$gtk_libs#g" -e "s#?libmpd_cflags#$libmpd_cflags#g" -e "s#?libmpd_libs#$libmpd_libs#g" -e "s#?glib_cflags#$glib_cflags#g" -e "s#?glib_libs#$glib_libs#g" -e "s#?applet_cflags#$applet_cflags#g" -e "s#?applet_libs#$applet_libs#g" -e "s#?sed#$sed#g" $1 > ${1%%.in}
+$sed -e "s#?cc#$cc#g" -e "s#?gtk_cflags#$gtk_cflags#g" -e "s#?gtk_libs#$gtk_libs#g" -e "s#?libmpd_cflags#$libmpd_cflags#g" -e "s#?libmpd_libs#$libmpd_libs#g" -e "s#?glib_cflags#$glib_cflags#g" -e "s#?glib_libs#$glib_libs#g" -e "s#?applet_cflags#$applet_cflags#g" -e "s#?sed#$sed#g" $1 > ${1%%.in}
 return
 }
 
@@ -82,16 +82,15 @@ fi
 libmpd_cflags=$($pkg_config_exe --cflags libmpd)
 libmpd_libs=$($pkg_config_exe --libs libmpd)
 
-check_exist libpanelapplet-2.0
-if [ $? -ne 0 ]
-then
-echo "aborting configure ..."
-exit 1
-fi
-
-applet_cflags=$($pkg_config_exe --cflags libpanelapplet-2.0)
-applet_libs=$($pkg_config_exe --libs libpanelapplet-2.0)
+#if [ $? -ne 0 ]
+#then
+#echo "aborting configure ..."
+#exit 1
+#fi
+#
+#applet_cflags=$($pkg_config_exe --cflags libpanelapplet-2.0)
+#applet_libs=$($pkg_config_exe --libs libpanelapplet-2.0)
 
 parse_in Makefile.in
 parse_in src/Makefile.in
-parse_in src/Makefile.applet.in
+#parse_in src/Makefile.applet.in
